# NumPy 

A package in python that is very important and a workhorse for data analysis 

Several other packages rely on NumPy for function, including the Pandas package (which we will get to!)

One important feature of NumPy is its work with arrays and that too multidimensional arrays!

In [45]:
import numpy as np 
#Gives the package the alias np

#Create arrays by giving the array function a list
mylist = [1, 2, 3]
myarray = np.array(mylist) # changed the square brackets to round brackets myarray = np.array[mylist]
myarray

array([1, 2, 3])

There are other functions from the package that initialize every value in an array to a specific value, all you have to do is specify array size

In [13]:
#An array consisting of all zeros, [0, 0, 0]:
zeros_array = np.zeros(3)

#An array consisting of all ones, [1, 1, 1]:
ones_array = np.ones(3)

#An array of random floats less than 1, [0.3056.., 0.7654.., 0.1234..]
random_array = np.random.random(3)

#The following code will create a 3x4 array of random numbers between 0 and 1
array1 = np.random.rand(3,4)
print(array1)

[[0.13665327 0.87878235 0.32425012 0.18713841]
 [0.8551332  0.40894211 0.95642512 0.67456517]
 [0.39812035 0.14390816 0.23186515 0.8736022 ]]


In [9]:
### Checing the shape and size of the array
#will print how many elements are in the array
array1.size


12

In [12]:
len(array1)

3

In [10]:
#This code will give shape of the array with 3 rows and 4 columns
array1.shape

(3, 4)

In [20]:
#Create an array with 1 row and 6 columns
array2 = np.arange(6)
array2

array([0, 1, 2, 3, 4, 5])

In [23]:
#To find out the datatype
array2.dtype

dtype('int64')

In [25]:
#To copy the array

array3 = array2.copy()
array3

array([0, 1, 2, 3, 4, 5])

### Selecting the element

In [28]:
#The command will select the element from index 2 to index 3 
array3[2:4]

array([2, 3])

## Arithemetic 

![SegmentLocal](https://media.giphy.com/media/c7PcKQlOqZ8Ws/200.gif "segemt")

Adding two arrays is as simple as adding two numbers!

In [44]:
first = np.array([1, 2, 3])

second = np.ones(3)

third = first + second
print(first)
print(second)
print(third)
#third will just be the indexes added together: [2, 3, 4]

[1 2 3]
[1. 1. 1.]
[2. 3. 4.]


This works the same with subtraction, multiplication, and division

Try multiplying an array by a single number! This is called broadcasting

In [40]:
myarray = np.array([1, 2, 3])
myarray

array([1, 2, 3])

In [43]:
newarray = myarray*4
newarray
#newarray will be myarray with every index multiplied by 4: [4, 8, 12]

array([ 4,  8, 12])

## Indexing 

We can get certain parts of an array the same way you get certain parts of a list

In [ ]:
myarray = np.array([1, 2, 3])

myarray[0] 
# What would this be?

myarray[1:]
#What about this?

myarray[0:2]
#And this?

## Helpful Functions!!

In [ ]:
my_array = np.array([2, 4, 6, 8])

my_max = my_array.max()

This function gives you the maximum value in the array, so my_max = 8

In [ ]:
my_min = my_array.min()

This function gives you the minimum value in the array, so my_min = 2

In [ ]:
my_sum = my_array.sum()

This function gives you the sum of the values in the array, so my_sum = 20 

In [ ]:
my_mean = my_array.mean()

This function gives you the mean of the values in the array, so my_mean = 5

In [ ]:
my_product = my_array.prod() 

This function gives you the product of the values in the array, so my_product = 432

# Multiple Dimensions

![SegmentLocal](https://media1.tenor.com/images/e5c21d98f56c4af119b4e14b6a9df893/tenor.gif?itemid=5437241 "segment")

NumPy can do everything above in multiple dimensions, with matrices 

In [38]:
#Creating a matrix!
arr = ([1,2], [3, 4])
my_matrix = np.array(arr)

ones_matrix = np.ones((3, 2))# ---> made the change here, instead of np.ones(3,2), I typed np.ones((3,2)) to get the desired array
#3 rows, 2 columns 

In [37]:
ones_matrix

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [34]:
my_matrix

array([[1, 2],
       [3, 4]])

Indexing works the same for each individual dimension, you just need to seperate by commas!

In [48]:
#To get 4
my_matrix[1][1]
#OR my_matrix[1,1]

4

In [ ]:
data = np.array([ [1, 2, 3, 4]
                  [5, 6, 7, 8]
                  [9, 0, 2, 4]
                  [6, 8, 3, 5] ])

data[0, 3]
#This would be the value in row 0, column 3, which is 3 

data[1:3]
#this would be the submatrix that includes row 1 and row 2, and all columns 

data[1:3, 0]
#This would be a sub matrix that includes row 1 and row 2, and only column 0

The helpful functions for arrays also apply to matrices

You can use some of them in new ways as well!

In [ ]:
data_max = data.max()
#This would work the same as with arrays, giving you the largest element in the matrix, 9

With .max(), you can now give it a parameter, the axis, that tells it to find the max in each row or each column 

In [ ]:
data_max0 = data.max(axis = 0)
#This would give you the max in each column, in an array

data_max1 = data.max(axis = 1)
#This would give you the max in each row, in an array

### Conditional Selection

In [53]:
arr = np.array([ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
print(arr < 5)
print(arr[arr<5])

[ True  True  True  True False False False False False False]
[1 2 3 4]


###Universal Array Function


In [55]:
#Square root
arr = np.array([1,4,9,16,25])
np.sqrt(arr)

array([1., 2., 3., 4., 5.])

In [56]:
#Exponential
arr = np.array([1,4,9,16,25])
np.exp(arr)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06,
       7.20048993e+10])

## Reshaping 

You can reshape your matrix in several different ways

The first useful way is transposing your matrix, so that it becomes flipped. The value in data(2, 3) would become the value in data(3, 2)
You do this by calling the T(): 

In [ ]:
data.T()

There is also a reshape function, and in the parameters you specify the parameters you want to make your matrix into:

In [ ]:
data.reshape(8, 2)
#Would make it from 4 rows and 4 columns to 8 rows and 2 columns 

## Uses!! 

NumPy package has many important uses for writing and fixing python code, here are a few examples

### Formulas 

Some formulas for problem solving with data can be long and complicated, but NumPy has many of the inner working of the equation as prewritten functions, such as squaring a number, and finding the sum!!

### Data Representation 

Many pieces of data are well suited to be represented by an array or matrix of some size, and then you have all the NumPy tools you've learned at your disposal! 